### ISSUE TITLE
Class 'SAPNWRFC\Connection' not found

### ISSUE THREAD

**Issue by gmuehl** [gkralik/php7-sapnwrfc#73] opened 2019-04-16 07:26 UTC
I have a decent problem in PHP 7.3. The Module ist compiled without errors. phpinfo() shows that it is available

![phpinfo](https://user-images.githubusercontent.com/151238/56189836-31fb7700-6029-11e9-8723-f6a8f22625d7.png)

I tried to use it in Zend Framework which worked well with PHP7.0, but with PHP7.3 i am getting this error:

 Error
 Class 'SAPNWRFC\Connection' not found

I tried all kinds of Use-Statements, i checked the Autoloader and checked the logs. There are simply no error messages regarding the Module. So, what could be wrong ?

**Comment by reeperbahnause** [comment] 2019-05-01 00:50
Same issue here except that I don't see sapnwrfc in phpinfo().  
But in the CLI with php -m the extension is shown.
I attached the build log, so you can see what happend.
[build.log](https://github.com/gkralik/php7-sapnwrfc/files/3133604/build.log)

**Comment by gkralik** [comment] 2019-05-01 13:54
@gmuehl can you give me some details (OS, exact PHP version, example code to reproduce)?
@reeperbahnause if you don't see sapnwrfc in your phpinfo() output, it is not loaded, so it won't work. Make sure to update the correct configuration file (CLI and FPM sometimes use different php.ini files).

**Comment by reeperbahnause** [comment] 2019-05-01 14:29
@gkralik  
I just found the reason for my issue. The extension was not loaded because the `sapnwrfc.dll` was nowhere in the `PATH` environment found. After I copied the, file the extension was loaded and as far as I can tell it works with PHP 7.3.4
There was one more issue when I tried to open the first connection. In the apache `error.log` I found the following:

> Could not open the ICU common library.  
   The following files must be in the path described by
   the environment variable "PATH":
   icuuc34.dll, icudt34.dll, icuin34.dll [nlsui0.c 1546] pid = 7068

These files seem to be old but adding them fixed the problem?!

Thank you for your work and your support!

**Comment by gkralik** [comment] 2019-05-01 14:35
Glad to hear it works.

Yes, ICU libraries are needed for the SAP NW RFC SDK to work.

**Comment by gkralik** [comment] 2019-05-03 11:47
@gmuehl do you still have the problem you described or can we close this issue?

**Comment by gmuehl** [comment] 2019-05-03 11:54
The problem still exists in PHP7.3.5 on Debian. Everything ok in phpinfo(); (see Screenshot), but if i do
a

$connection = new SAPNWRFC\Connection($parameters);

It tells me that the Class can't be found. Tried it with \SAPNWRFC too, end i tried it with a USE. Always the same result: Class not found

**Comment by gkralik** [comment] 2019-05-03 12:00
Strange.
What's the output of
```php
var_dump(extension_loaded('sapnwrfc'));
```
What version of Debian, Apache/nginx/whatever are you using?

**Comment by gmuehl** [comment] 2019-05-03 12:22
Hi Gregor

looks like i have lied about the PHP-Version :D

> PHP-Version 7.3

> System:
> No LSB modules are available.
> Distributor ID: Debian
> Description:    Debian GNU/Linux 9.8 (stretch)
> Release:        9.8
> Codename:       stretch
> 

> Apache:
> Apache/2.4.25 (Debian) OpenSSL/1.0.2r configured -- resuming normal operations

Output of var_dump

> bool(true)

**Comment by gmuehl** [comment] 2019-05-03 12:26
My Fault! You can close the ticket. The Module was enabled in Apache, but not in PHP Cli.

**Comment by gkralik** [comment] 2019-05-03 12:27
Ah, something like that would ave been my next question/hint. Glad to hear it works.

**Closed by gkralik** 2019-05-03 12:27 UTC

**Comment by didinosing** [comment] 2020-09-16 05:15
> My Fault! You can close the ticket. The Module was enabled in Apache, but not in PHP Cli.

Can you describe the solving case? Thanks

**Comment by goalmaker** [comment] 2021-08-30 10:56
> My Fault! You can close the ticket. The Module was enabled in Apache, but not in PHP Cli.

I am also facing the same issue with version php 7.3.8 - nts, using 1.3.0 sapnwrfc precompiled dll loaded in php
![image](https://user-images.githubusercontent.com/2524176/131324548-db5c2687-d4ce-4000-9b52-546b5004a048.png)

![image](https://user-images.githubusercontent.com/2524176/131324644-ba3c0d0d-34bc-419f-beef-af5c5ad2b8c8.png)

![image](https://user-images.githubusercontent.com/2524176/131328758-b356d984-a901-497a-8163-58d35c02870a.png)

code: 
```
use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;


    $config = [
        'ASHOST' => 'xxx.xx.xx.xx',
        'SYSNR'  => '00',    
        'CLIENT' => '600',
        'USER'   => 'XXXX',
        'PASSWD' => 'XXXX',
        'LANG' => 'EN',
        'trace'  => SapConnection::TRACE_LEVEL_OFF
    ];

 
    $connection = new SapConnection($config);
```

Output
Hi testing Vivan 30-Aug-2021 02:52:38 pm
Fatal error: Uncaught SAPNWRFC\ConnectionException: Could not open connection in C:\inetpub\wwwroot\DigiBrainAhlaan\index.php:67 Stack trace: #0 C:\inetpub\wwwroot\DigiBrainAhlaan\index.php(67): SAPNWRFC\Connection->__construct(Array) #1 {main} thrown in C:\inetpub\wwwroot\DigiBrainAhlaan\index.php on line 67

**Comment by gkralik** [comment] 2021-08-30 10:59
@goalmaker Please do not comment on closed issues. If you have a problem, open another issue.

**Comment by goalmaker** [comment] 2021-08-30 11:30
sorry @gkralik  I will open it as new issue
